config:
  logging:
    fields:
      add:
        backend: backend
binds:
- port: 3000
  listeners:
  - routes:
    - backends:
      - host: localhost:9999
      policies:
        cors:
          allowOrigins:
          - '*'
          allowHeaders:
          - '*'
          allowMethods:
          - GET
          - POST
          - OPTIONS
          exposeHeaders:
          - '*'
          allowCredentials: false
        a2a: {}
        localRateLimit:
        - maxTokens: 1
          tokensPerFill: 1
          fillInterval: 1000s
          type: tokens
